"""Add unique constraint

Revision ID: 22434124b09f
Revises: 2ad145911582
Create Date: 2023-10-22 07:43:28.305364

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22434124b09f"
down_revision: Union[str, None] = "2ad145911582"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_idx_uid_tmiline_id", "anonymous_post", ["user_id", "timeline_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_idx_uid_tmiline_id", "anonymous_post", type_="unique")
    # ### end Alembic commands ###
