"""create tables

Revision ID: 2ad145911582
Revises: 
Create Date: 2023-10-15 16:29:02.747362

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ad145911582'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_map_shop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_map_shop_id', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_map_shop_id'),
    comment='GoogleMapのshopIdに対応した情報を、APIを叩く回数を減らすために保存する。'
    )
    op.create_table('anonymous_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('google_map_shop_id', sa.String(length=200), nullable=False),
    sa.Column('star', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['google_map_shop_id'], ['google_map_shop.google_map_shop_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Swipe UIに使用する匿名投稿用のテーブル'
    )
    op.create_table('anonymous_post_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anonymous_post_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anonymous_post_id'], ['anonymous_post.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Swipe UIに使用する匿名投稿用の画像パスを保存するテーブル'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anonymous_post_image')
    op.drop_table('anonymous_post')
    op.drop_table('google_map_shop')
    # ### end Alembic commands ###
