name: Test And Format On Server
on:
  push:
    branches: [master, develop]
    paths:
      - Server/**/*
  pull_request:
    paths:
      - Server/**/*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Check poetry
        run: |
          poetry --version
          poetry config --list

      - name: Install Dependencies
        run: |
          poetry lock
          poetry install

      - name: Type Check
        run: |
          poetry run poe type

      - name: Format Check
        run: poetry run poe format-check
